swoole:
  http_server:
    port:          '%env(HTTP_SWOOLE_PORT)%'
    host:          localhost
    running_mode:  'process'
    socket_type:   tcp
    ssl_enabled:   false
    trusted_hosts: localhost,127.0.0.1
    trusted_proxies:
      - '*'
    static:
      strategy:   'advanced'
      public_dir: '%kernel.project_dir%/public'
    hmr: 'off'
    services:
      debug_handler:                   false
      trust_all_proxies_handler:       false
      cloudfront_proto_header_handler: false
      entity_manager_handler:          true
    settings:
      worker_count:   '%env(int:SWOOLE_WORKERS_COUNT)%'
      log_file:       'php://stdout'
      log_level:      error
      pid_file:       '/var/run/swoole_http_server.pid'
