version: '3.7'

services:
  php:
    build:
      context: docker/php
      args:
        - uid=1000
        - gid=82
    tty: true
    volumes:
      - ./:/var/www/project:rw
    extra_hosts:
      - "docker-host.localhost:127.0.0.1"
    ports:
      - ${HTTP_SWOOLE_PORT}:${HTTP_SWOOLE_PORT}
      - ${HTTP_WORKERMAN_PORT}:${HTTP_WORKERMAN_PORT}
    links:
      - db
      - redis
    cpus: '4'
  db:
    image: mysql:8.0.21
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - speedtest-db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    build:
      context: ./docker/nginx
      args:
        - uid=1000
        - gid=82
    ports:
      - ${HTTP_NGINX_PORT}:80
    links:
      - php
    volumes:
      - ./var/log/nginx:/var/log/nginx:cached
      - ./:/var/www/project:cached

  redis:
    image:   redis:6.2.1-alpine3.13
    restart: always

volumes:
  speedtest-db-data:
