framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
        app:    cache.adapter.redis
        system: cache.adapter.system
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
            doctrine.second_level_cache_pool:
                adapter: cache.adapter.redis
