monolog:
    handlers:
        main:
            type:                fingers_crossed
            action_level:        error
            handler:             nested
            excluded_http_codes: [404, 405]
            buffer_size:         50
        nested:
            type:      stream
            path:      "php://stdout"
            level:     error
            formatter: 'monolog.formatter.json'
        console:
            type:      stream
            path:      "php://stdout"
            level:     error
            formatter: 'monolog.formatter.json'
